### ISSUE TITLE
PROXY IS NOT WORKING AT ALL

### ISSUE THREAD

**Issue by vannkezz** [WubbaLubbaDubDubDev/notpixel_bot_advanced#28]

**Comment by WubbaLubbaDubDubDev** [comment]
> 
1. When was the last time you updated the script?


2. Could you provide the logs so we can understand the issue?

**Comment by vannkezz** [comment]
```
Traceback (most recent call last):
  File "/home/c9user/daily/garapan/pyrogram/notpixel-wubba/main.py", line 4, in <module>
    from bot.utils import logger
  File "/home/c9user/daily/garapan/pyrogram/notpixel-wubba/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/c9user/daily/garapan/pyrogram/notpixel-wubba/bot/utils/launcher.py", line 41, in <module>
    proxy_chain = ProxyChain()
  File "/home/c9user/daily/garapan/pyrogram/notpixel-wubba/bot/utils/proxy_chain.py", line 9, in __init__
    self.load_proxies_from_json()
  File "/home/c9user/daily/garapan/pyrogram/notpixel-wubba/bot/utils/proxy_chain.py", line 14, in load_proxies_from_json
    data = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 222)
```


proxy format: http://username:password@hostname:port

I used 1 rotating proxy for 100+ accs

**Comment by vannkezz** [comment]
nevermind is working now, my fault not checking the accounts.json
